FROM nginx:1.23-alpine-perl

COPY ./deploy/nginx/prod.conf /etc/nginx/nginx.conf
COPY . /var/www/html

# depends on the actual path on the host; manually copy the files to repository after generating them with certbot
