FROM php:8.0-fpm-alpine

RUN apk add --no-cache --update --virtual buildDeps \
    autoconf \
    pcre-dev \
    gcc \
    make \
    g++ \
    zlib-dev

RUN pecl install redis
RUN docker-php-ext-enable redis
COPY docker/php-fpm/redis.ini /usr/local/etc/php/conf.d/redis.ini

RUN docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-enable pdo_mysql

RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

RUN apk add --update nodejs npm

COPY docker/php-fpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN pecl install xdebug && \
 docker-php-ext-enable xdebug;

RUN apk del buildDeps

RUN addgroup -g 1000 -S docker-www-data; \
    adduser -u 1000 -D -S -G docker-www-data docker-www-data
USER docker-www-data

EXPOSE 9000
CMD ["php-fpm"]
