FROM php:8.1-fpm-alpine3.16 AS final

RUN apk add --no-cache --update --virtual buildDeps \
    autoconf \
    pcre-dev \
    gcc \
    make \
    g++ \
    zlib-dev

RUN pecl install redis
RUN docker-php-ext-enable redis

RUN docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-enable pdo_mysql


COPY ./deploy/php-fpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
ARG XDEBUG_ON
RUN if [[ "$XDEBUG_ON" == '1' ]]; then \
  pecl install xdebug && \
  docker-php-ext-enable xdebug; \
fi

RUN apk del buildDeps

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html

EXPOSE 9000
CMD ["php-fpm"]
