FROM composer AS build
WORKDIR /build

COPY . /build
RUN composer install --no-dev && \
composer dumpautoload --optimize

FROM php:8.0-fpm-alpine AS final

RUN apk add --no-cache --update --virtual buildDeps \
    autoconf \
    pcre-dev \
    gcc \
    make \
    g++ \
    zlib-dev

RUN pecl install redis
RUN docker-php-ext-enable redis

RUN docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-enable pdo_mysql

COPY ./deploy/php-fpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN pecl install xdebug && \
 docker-php-ext-enable xdebug;

RUN apk del buildDeps

COPY --from=build /build /var/www/html
RUN chown -R www-data:www-data /var/www/html

EXPOSE 9000
CMD ["php-fpm"]
