version: '3.8'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile.php.production
    restart: always
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx.production
    restart: always
    depends_on:
      - php-fpm
    ports:
      - '80:80'
      - '443:443'
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - "mysql:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
volumes:
  mysql:
